### ISSUE TITLE
Self-payments not allowed at coinos.io

### ISSUE THREAD

**Issue by jerzybrzoska** [asoltys/coinos#17] opened 2020-11-27 16:29 UTC
When trying to send from one [coinos](https://coinos.io) account to another I get the following:
![payto_2020-12-30_10-49-33](https://user-images.githubusercontent.com/51721153/103343894-6c22db80-4a8d-11eb-94df-27c9898261b7.png)
![Screenshot_2020-12-30_10-50-18](https://user-images.githubusercontent.com/51721153/103343910-7513ad00-4a8d-11eb-839a-2651033fc870.png)
The issue only happens when I have two coinos accounts logged in at the same time in my tor browser (in two different tabs). Everything works well when I access the two accounts from two different browsers, let's say Chrome and Firefox. 
Is it because the accounts are hosted by the same node? Is there any work around this issue (other than self-hosting a full node)?

**Comment by asoltys** [comment] 2020-11-27 19:39
Coinos is supposed to detect when you're paying another user and send it internally instead of over the lightning network. I tried to reproduce just now and it detected properly for me so not sure why it didn't work for you in this case.

**Comment by asoltys** [comment] 2020-11-27 19:42
![image](https://user-images.githubusercontent.com/7641/100480256-9c99e300-30a5-11eb-8fcb-1ee373cb269d.png)

**Comment by asoltys** [comment] 2020-12-28 16:59
Closing for now since I can't reproduce

**Comment by jerzybrzoska** [comment] 2020-12-30 10:00
I figured out when the issue does not happen. Everything works well when I access the two accounts from two different browsers, let's say Chrome and Firefox. The issue only happens when I have two coinos accounts logged in at the same time in my tor browser (in two different tabs). Then the issue happens. I updated my screenshots in my first post. As you can see, when accessing the accounts at the same time from a Tor browser the server does not detect that the payment is going to be internal.

**Comment by asoltys** [comment] 2020-12-30 16:47
Thanks for the update I'll try again with Tor

**Comment by asoltys** [comment] 2020-12-30 17:44
I tested with Tor browser and still wasn't able to reproduce the issue. Is it possible your tor browser has some setting that's disabling websockets? The coinos server sends a message to the client over a websocket connection when it detects an internal transfer so I suspect you're not getting that message for some reason.

**Comment by asoltys** [comment] 2020-12-30 17:53
Actually I am having an issue with websockets myself now when I access it at with Tor at coinos.io instead of the onion site. I'll have to investigate more to see if I can figure out why but in the meantime you can try using the onion url: http://uzmim34vid5dkyzjxpel6zbkfz4qeqaaqe3gqrtbmekhxqglvzau73ad.onion/

**Comment by asoltys** [comment] 2020-12-30 22:06
I still haven't been able to figure out the root cause of this so I've just put in place a javascript redirect that should automatically send you to the onion site if you're using tor browser.

**Closed by asoltys** 2020-12-30 22:06 UTC
